version: "3"
services:
  app:
    build:
      context: .
      dockerfile: ./Dockerfile
    working_dir: /go/src/slackbot
    environment:
      - GO111MODULE=on
    volumes:
      - .:/go/src/slackbot
    command: [ 'tail', '-f', '/dev/null']
    networks:
      default:
